In [1]:
import pandas as pd
from pandas import DataFrame
from pandas import Series

In [2]:
df = pd.read_excel('Naver_Report.xls', skiprows=[0])
df.head() # default 5 rows

,광고그룹,키워드,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
0,올인원 패키지 : 디자인 툴_파워컨텐츠_포토샵,-,2319456,9606.0,0.414149,261.549448,2512444
1,올인원 패키지 : 업무자동화_VBA,-,767491,8058.0,1.049915,295.974808,2384965
2,ㅍAOP 전체_중복키워드_디자인(삭제),일러스트,1137840,324.0,0.028475,4841.663580,1568699
3,올인원 패키지 : 데이터 분석 입문 온라인_파콘,-,694106,1863.6,0.268489,630.593475,1175174
4,3. html,HTML,9626374,813.6,0.008452,1408.435349,1145903

In [3]:
#head() - first 10 rows
df.head(10)

,광고그룹,키워드,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
0,올인원 패키지 : 디자인 툴_파워컨텐츠_포토샵,-,2319456,9606.0,0.414149,261.549448,2512444
1,올인원 패키지 : 업무자동화_VBA,-,767491,8058.0,1.049915,295.974808,2384965
2,ㅍAOP 전체_중복키워드_디자인(삭제),일러스트,1137840,324.0,0.028475,4841.663580,1568699
3,올인원 패키지 : 데이터 분석 입문 온라인_파콘,-,694106,1863.6,0.268489,630.593475,1175174
4,3. html,HTML,9626374,813.6,0.008452,1408.435349,1145903
5,6. 파이썬,파이썬,384522,260.4,0.067720,3705.360983,964876
6,1. 코딩,코딩,562162,271.2,0.048242,3243.215339,879560
7,2. C언어 일반,C언어,271370,153.6,0.056602,5269.257812,809358
8,프로그래밍 전체_파워컨텐츠_블록체인(삭제),가상화폐,91369,2838.0,3.106086,283.217054,803770
9,AOP 전체_중복키워드_디자인,포토샵,1887822,393.6,0.020849,1913.737297,753247

In [4]:
#tail() - prints out last 5 rows
df.tail()

,광고그룹,키워드,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
1376,올인원 패키지 : 업무자동화_3. 엑셀,엑셀셀서식,24016,0.0,0.0,0.0,0
1377,올인원 패키지 : 업무자동화_3. 엑셀,MATCH,32287,0.0,0.0,0.0,0
1378,마케팅KPI수립,LTV,32602,0.0,0.0,0.0,0
1379,data_camp_rmp_8,DECISION,60844,0.0,0.0,0.0,0
1380,4. 웹의 동작,REST,61193,0.0,0.0,0.0,0

In [5]:
df.tail(10)

,광고그룹,키워드,노출수,클릭수,클릭률(%),"평균클릭비용(VAT포함,원)","총비용(VAT포함,원)"
1371,7. 운영체제,가상머신,16605,0.0,0.0,0.0,0
1372,파이낸스 전체,부동산책,16722,0.0,0.0,0.0,0
1373,ㅍ올인원 패키지 : UX/UI 디자인 입문_연관검색어(삭제),VD,17504,0.0,0.0,0.0,0
1374,AOP 전체_중복키워드_디자인,포토샵단축키,18818,0.0,0.0,0.0,0
1375,올인원 패키지 : 업무자동화_3. 엑셀,SUMIF,23549,0.0,0.0,0.0,0
1376,올인원 패키지 : 업무자동화_3. 엑셀,엑셀셀서식,24016,0.0,0.0,0.0,0
1377,올인원 패키지 : 업무자동화_3. 엑셀,MATCH,32287,0.0,0.0,0.0,0
1378,마케팅KPI수립,LTV,32602,0.0,0.0,0.0,0
1379,data_camp_rmp_8,DECISION,60844,0.0,0.0,0.0,0
1380,4. 웹의 동작,REST,61193,0.0,0.0,0.0,0

In [6]:
#shape - dataframe의 크기(row, num of columns)
df.shape

(1381, 7)

In [7]:
# describe() - statistics for each columns
df.describe()

                노출수          클릭수       클릭률(%)  평균클릭비용(VAT포함,원)  총비용(VAT포함,원)
count  1.381000e+03  1381.000000  1381.000000      1381.000000  1.381000e+03
mean   3.505415e+04    52.530630     0.352871       981.631682  3.791958e+04
std    2.964650e+05   387.502772     1.000468      1372.390031  1.421492e+05
min    1.001000e+03     0.000000     0.000000         0.000000  0.000000e+00
25%    1.814000e+03     1.200000     0.007152        64.166667  7.700000e+01
50%    3.805000e+03     3.600000     0.061031       395.976793  2.123000e+03
75%    1.073400e+04    14.400000     0.237026      1302.812500  1.743500e+04
max    9.626374e+06  9606.000000    13.587402      9362.527778  2.512444e+06

In [8]:
# pandas setting options - express in float 
pd.set_option('display.float_format', '{:.2f}'.format)

In [9]:
#describe()
df.describe()

             노출수     클릭수  클릭률(%)  평균클릭비용(VAT포함,원)  총비용(VAT포함,원)
count    1381.00 1381.00 1381.00          1381.00       1381.00
mean    35054.15   52.53    0.35           981.63      37919.58
std    296465.03  387.50    1.00          1372.39     142149.16
min      1001.00    0.00    0.00             0.00          0.00
25%      1814.00    1.20    0.01            64.17         77.00
50%      3805.00    3.60    0.06           395.98       2123.00
75%     10734.00   14.40    0.24          1302.81      17435.00
max   9626374.00 9606.00   13.59          9362.53    2512444.00

In [10]:
#columns - returns name of columns
df.columns

Index(['광고그룹', '키워드', '노출수', '클릭수', '클릭률(%)', '평균클릭비용(VAT포함,원)',
       '총비용(VAT포함,원)'],
      dtype='object')

In [11]:
#unique() - unique row (series)
#df['광고그룹']
df['광고그룹'].unique()

array(['올인원 패키지 : 디자인 툴_파워컨텐츠_포토샵', '올인원 패키지 : 업무자동화_VBA',
       'ㅍAOP 전체_중복키워드_디자인(삭제)', '올인원 패키지 : 데이터 분석 입문 온라인_파콘', '3. html',
       '6. 파이썬', '1. 코딩', '2. C언어 일반', '프로그래밍 전체_파워컨텐츠_블록체인(삭제)',
       'AOP 전체_중복키워드_디자인', '디지털 마케팅 스쿨 13기_대표키워드', '인스타그램 마케팅',
       '블록체인 신사업 시작하기', 'AOP 전체_중복키워드_비지니스', '올인원 패키지 : 업무자동화_2. 파이썬',
       '올인원 패키지 : 1인 쇼핑몰 시작하기_00.창업_PC', '올인원 패키지 : 영상 제작/편집_6.프리미어프로',
       '1. 모바일앱개발_교육', '올인원 패키지 : UX/UI 디자인 입문_연관검색어',
       '올인원 패키지 : 데이터 분석 입문(파컨)', 'JavaScript BOOT CAMP', '1. 일반_PC',
       'AOP 전체_중복키워드_공통', 'AOP 전체_중복키워드_프로그래밍', '003.퍼포먼스 마케팅',
       '2. 프로그래밍', '마케팅 유치원', '올인원 패키지 : 업무자동화_1. 자동화', '올인원 패키지 : 브랜딩',
       'ㅍ올인원 패키지 : 브랜딩', '올인원 패키지 : 콘텐츠 마케팅_카피라이팅',
       'AOP 전체_중복키워드_데이터사이언스', '8. 시스템 프로그래밍',
       'ㅍ올인원 패키지 : UX/UI 디자인 입문_연관검색어(삭제)', '올인원 패키지 : 프로그래밍 첫걸음 시작하기',
       '페이스북&인스타그램 마케팅 실전', 'Python & Django를 활용한 웹 서비스_개발자', '5. 자료구조',
       'fin_camp_auction_6', '올인원 패키지 : 1인 쇼핑몰_00.창업_MO', '타이포그래피와 편집디자인',
       '올인원 패키지 : 디지털 마케팅_1. 디지털 마케팅', 'AOP 전체_중복키워드_마케팅',
       '마케터를 위한 데이터 부트캠프', '코딩으로 여행하는 블록체인 서비스',
       '올인원 패키지 : 1인 쇼핑몰 시작하기_02.쇼핑몰구축', '상업용 부동산 실무 입문 4기',
       '포토샵 유치원_일러스트레이터 유치원', '고객의 마음을 읽는 구글애널리틱스',
       '왕초보의 파이썬 웹 프로그래밍 CAMP', '올인원 패키지 : 콘텐츠 마케팅_영상바이럴', '마케팅KPI수립',
       '프로그래밍 유치원', 'ㅍAOP 전체_중복키워드_프로그래밍(삭제)', '#000_마케팅 전체_main',
       'SEO/SEM 전략', '올인원 패키지 : 투자_파워콘텐츠', 'ㅍAOP 전체_중복키워드_공통(삭제)',
       '올인원 패키지 : 콘텐츠 마케팅_대표키워드', '올인원 패키지 : 파이썬 웹 개발_2.프론트엔드기초',
       '올인원 패키지 : 업무자동화_4. VBA', '올인원 패키지 : 금융공학/퀀트_01.파이썬기본&자동화',
       'TensorFlow로 시작하는 딥러닝 입문', '올인원 패키지 : 업무자동화_3. 엑셀', '002.마케팅 입문',
       '올인원 패키지 : 그로스해킹_5.마케팅 분석', '1. 데이터분석입문_일반', 'data_camp_rmp_8',
       'ㅍAOP 전체_중복키워드_마케팅(삭제)', '올인원 패키지 : 게임 개발', '마케터를 위한 데이터 해석 실전',
       '마케팅 전체', '1. 경영 일반', 'Vue로 구현하는 PWA CAMP', '1. 전체',
       '001.데이터분석/ 통계', '5. javascript', 'ㅍ1. 전체',
       '올인원 패키지 : 1인 쇼핑몰 시작하기_05.상품촬영', '1. 컴퓨터공학 일반',
       '올인원 패키지 : 파이썬 웹 개발_3.FLASK기초', '올인원 패키지 : 디지털 마케팅_2. 페이스북 광고',
       '올인원 패키지 : 영상 제작/편집_2.영상제작이론', '대기업을 이기는 브랜딩 전략',
       '올인원 패키지 : 영상 제작/편집_9.유튜브/유튜버', '올인원 패키지 : 금융공학/퀀_03.금융공학',
       '올인원 패키지 : 리더를 위한 HR/인재경영_1.인재', '내 아이템에 맞는 영상 콘텐츠 기획/제작',
       'ㅍAOP 전체_중복키워드_데이터사이언스(삭제)', '올인원 패키지 : 그로스해킹_1.용어',
       '1_벤처캐피탈에 대한 이해(벤처캐피탈)', '1. 일반_MO', '002.R',
       'PYTHON & DJANGO를 활용한  웹 서비스 개발', '올인원 패키지 : 디지털 마케팅_3. 구글 광고',
       '올인원 패키지 : 1인 쇼핑몰 시작하기_06.해외쇼핑몰', 'LaTeX를 활용한 효율적 논문작성 Workshop',
       '인디자인 유치원', 'ㅍAOP 전체_중복키워드_비지니스(삭제)', '딥러닝으로 배우는 병렬처리 CAMP',
       '올인원 패키지 : 영상 제작/편집_3.촬영 기법/장비1', '올인원 패키지 : FAST MBA_파워컨텐츠_아마존',
       '7. 운영체제', '실전 웹/앱 프로젝트 기획', '2_투자유치를 위한 사업계획서 작성(투자유치)',
       '올인원 패키지 : 영상 제작/편집_10.패캠강의', '올인원 패키지 : 1인 쇼핑몰 시작하기_01.플랫폼',
       '다빈치리졸브와 컬러그레이딩', '파이썬을 통한 금융 데이터 수집과 분석 자동화 16기',
       '실전 웹 UX/UI 디자인', '올인원 패키지 : 영상 제작/편집_7.에프터이펙트', '파이썬 텍스트 마이닝',
       'data_camp_pcda_3', '5_초기 스타트업 실제 투자사례(창업자)', '1. 모바일앱개발_세부',
       'Python & Django를 활용한 웹 서비스_일반', '005.머신러닝',
       '올인원 패키지 : 영상 제작/편집_5.일러스트', '구글 광고', '올인원 패키지 : 영상 제작/편집_1.크리에이터',
       '딥러닝으로 배우는 병렬처리 CAMP_구버전', '건강한 조직을 만드는 HR 전략 WORKSHOP',
       '6.  컴퓨터구조', '003.파이썬', 'fin_camp_modeling_15', 'Apache Spark',
       '올인원 패키지 : 금융공학/퀀_02.R활용금융데이터분석', '모바일 앱 UX/UI 디자인',
       '001.BASIC DESIGN', '올인원 패키지 : 영상 제작/편집_8.파이널컷 프로',
       '1. 앱웹서비스기획_일반', '프로그래밍 전체', '리눅스 인프라',
       'OpenCV와 함께하는 컴퓨터 비전 프로그래밍', '서비스 기획 스쿨 5기_구글 연관검색어',
       '올인원 패키지 : 금융공학/퀀트_00.일반', '올인원 패키지 : 리더를 위한 HR/인재경영_2.리더십',
       '4_벤처캐피탈 투자계약(벤처 투자)', 'fin_camp_rdev_4', '파이낸스 전체',
       'typescript 실전 workshop', '비즈니스 전체', '4. css', '영상 콘텐츠 디자인 유치원',
       '올인원 패키지 : 디지털 마케팅_5. 태그매니저', '007.빅데이터',
       '모바일 앱 GUI 포트폴리오 디자인 LAB', '올인원 패키지 : 디지털 마케팅_8. 검색 마케팅',
       'Javascript 정복 프로젝트', '올인원 패키지 : 콘텐츠 마케팅_콘텐츠 제작',
       '올인원 패키지 : 디지털 마케팅_트위터광고', '올인원 패키지 : 1인 쇼핑몰 시작하기_04.호스팅사',
       '쉽고 재미있는 재무제표 분석 17기', '1_2 대표 경쟁', 'Java 웹 프로그래밍 마스터 4기 : 3개월',
       '올인원 패키지 : 그로스해킹_2.그로스해킹', '크리에이티브 전체', '002.UX/UI',
       'fin_camp_feasibilitystudy_18', 'Vue.js 정복 CAMP', '4. 웹의 동작',
       '머신러닝을 위한 선형대수학', '6_스타트업 M&A에 대한 단상(스타트업)', 'iOS 개발 스쿨 9기_기존 키워드',
       '006.딥러닝', 'UX 디자인 실전', '디지털 마케팅', '올인원 패키지 : 리더를 위한 HR/인재경영_5.HR',
       '올인원 패키지 : 영상 제작/편집_4.포토샵', '데이터 사이언스 전체',
       '올인원 패키지 : 파이썬 웹 개발_4.Django', '올인원 패키지 : 리더를 위한 HR/인재경영_3.온보딩',
       '3. 파이썬', '컴퓨터공학으로 풀어낸 블록체인 코어 CAMP', '7_How to 벤처캐피탈',
       '3_기업가치평가 방법론', '자율주행 연구를 위한 ROS·SLAM Workshop',
       '프론트엔드 개발 스쿨 12기_기존 키워드', '개발자와 협업하는 디자이너를 위한 실무 역량 강화',
       '올인원 패키지 : 1인 쇼핑몰 시작하기_03.결제시스템', '웹 프로그래밍 스쿨 10기_기존 키워드',
       '올인원 패키지 : 디지털 마케팅_인스타광고', '다함께 DDD 프로젝트', 'fin_camp_rfs_9',
       'Hyperledger Fabric 프로젝트 CAMP', 'fin_camp_business_4'],
      dtype=object)

In [12]:
#len, unique()
#df['광고그룹']
len(df['광고그룹'].unique())

186

In [13]:
#unique()
df['키워드'].unique()

array(['-', '일러스트', 'HTML', ..., 'MATCH', 'DECISION', 'REST'],
      dtype=object)

In [14]:
# len, unique()
len(df['키워드'].unique())

1112

In [15]:
# value_counts() - frequency of unique value in column
#df['광고그룹']
df['광고그룹'].value_counts()

올인원 패키지 : 업무자동화_3. 엑셀           93
AOP 전체_중복키워드_디자인                57
#000_마케팅 전체_main                48
ㅍAOP 전체_중복키워드_디자인(삭제)           46
타이포그래피와 편집디자인                   26
                                ..
fin_camp_rfs_9                   1
올인원 패키지 : 영상 제작/편집_5.일러스트        1
올인원 패키지 : 콘텐츠 마케팅_콘텐츠 제작         1
Hyperledger Fabric 프로젝트 CAMP     1
올인원 패키지 : 디지털 마케팅_트위터광고          1
Name: 광고그룹, Length: 186, dtype: int64

In [16]:
# value_counts() - frequency of unique value in column
#df['키워드']
df['키워드'].value_counts()

-          8
GUI        5
포토샵        5
구글광고       5
퍼포먼스마케팅    4
          ..
쇼핑몰재고관리    1
BIGDATA    1
벽화알바       1
PICKLE     1
CHATBOT    1
Name: 키워드, Length: 1112, dtype: int64

In [17]:
# sort_values() - sort(default : ascending) value in column
#df['노출수']
df['노출수'].sort_values()

1057       1001
445        1003
597        1005
983        1006
442        1007
         ...
13      1470452
9       1887822
0       2319456
173     3095998
4       9626374
Name: 노출수, Length: 1381, dtype: int64

In [18]:
# sort_values() - sort(default : descending) value in column
#df['노출수']
df['노출수'].sort_values(ascending=False)

4       9626374
173     3095998
0       2319456
9       1887822
13      1470452
         ...
442        1007
983        1006
597        1005
445        1003
1057       1001
Name: 노출수, Length: 1381, dtype: int64

In [19]:
# sort_values() - sort(default : ascending) value in column
#df['클릭수']
df['클릭수'].sort_values()

1380      0.00
1159      0.00
1160      0.00
1161      0.00
1162      0.00
         ...
26     2535.60
83     2798.40
8      2838.00
1      8058.00
0      9606.00
Name: 클릭수, Length: 1381, dtype: float64

In [20]:
# sort_values() - sort(default : descending) value in column
#df['클릭수']
df['클릭수'].sort_values(ascending=False)

0      9606.00
1      8058.00
8      2838.00
83     2798.40
26     2535.60
         ...
1162      0.00
1161      0.00
1160      0.00
1159      0.00
1380      0.00
Name: 클릭수, Length: 1381, dtype: float64